intro:
title: An Optimistic Perspective on Offline Reinforcement Learning
description:
- International Conference on Machine Learning (ICML) 2020. 
- An earlier version was titled "Striving for Simplicity in Off-Policy Deep Reinforcement Learning" and presented as a contributed talk at NeurIPS 2019 Deep RL Workshop. 
buttons:
  DQN Replay Dataset: https://research.google/tools/datasets/dqn-replay/
  Blog: https://ai.googleblog.com/2020/04/an-optimistic-perspective-on-offline.html
  Paper: 'https://arxiv.org/abs/1907.04543'
  Code: 'https://github.com/google-research/batch_rl'
  Slides: 'pdfs/slides.pdf'
  Poster: 'pdfs/neurips_drl_poster.pdf'
  Talk: 'https://slideslive.com/38922701/contributed-talk-striving-for-simplicity-in-offpolicy-deep-reinforcement-learning' 
  Authors: '#authors'
