intro:
title: An Optimistic Perspective on Offline Reinforcement Learning
description:
- International Conference on Machine Learning (ICML) 2020. 
- An earlier version was titled "Striving for Simplicity in Off-Policy Deep Reinforcement Learning" and presented as a contributed talk at NeurIPS 2019 Deep RL Workshop. 
buttons:
  DQN Replay Dataset: https://research.google/tools/datasets/dqn-replay/
  Blog: https://ai.googleblog.com/2020/04/an-optimistic-perspective-on-offline.html
  Paper: 'https://arxiv.org/pdf/1907.04543.pdf'
  Code: 'https://github.com/google-research/batch_rl'  
  Talk: 'https://icml.cc/virtual/2020/poster/6643'
  Slides: 'https://docs.google.com/presentation/d/1ROltXr6FIeYKrnGl0tKHGWI0pL4Zo8CnvAK2-cdpQyY/edit?usp=sharing'
  Talk (NeurIPS): 'https://slideslive.com/38922701/contributed-talk-striving-for-simplicity-in-offpolicy-deep-reinforcement-learning'
  Poster (NeurIPS): 'pdfs/neurips_drl_poster.pdf'
  Authors: '#authors'
